AWSTemplateFormatVersion: 2010-09-09

Resources:

  ECSCluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: CFNCluster

  taskdefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      containerDefinitions:
        - essential: true
          image: '968127021175.dkr.ecr.eu-central-1.amazonaws.com/ingrid:latest'
          logConfiguration:
            logDriver: awslogs
            options:
              awslogs-create-group: true
              awslogs-group: /ecs/fargate-task-definition
              awslogs-region: eu-central-1
              awslogs-stream-prefix: ecs
          name: sample-fargate-app
          portMappings:
            - containerPort: 80
              hostPort: 80
              protocol: tcp
      cpu: '256'
      executionRoleArn: 'arn:aws:iam::968127021175:role/ecsTaskExecutionRole'
      family: task-definition-cfn
      memory: '512'
      networkMode: awsvpc
      requiresCompatibilities:
        - FARGATE
      runtimePlatform:
        OperatingSystemFamily: LINUX

  ECSService:
    Type: 'AWS::ECS::Service'
    Properties:
      ServiceName: cfn-service
      Cluster: !Ref ECSCluster
      DesiredCount: 1
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          SecurityGroups:
            - sg-02beaba3c1e3369f1
          Subnets:
            - subnet-0bb6ebebf7e04c2a5
      TaskDefinition: !Ref taskdefinition



















#---
#AWSTemplateFormatVersion: '2010-09-09'
#Description: The template used to create an ECS Service from the ECS Console.
#
#Parameters:
#
#  ECSClusterName:
#    Type: String
#    Default: testSerrano
#
#  SecurityGroupIDs:
#    Type: CommaDelimitedList
#    Default: sg-0ce7a019709f33ca9
#
#  SubnetIDs:
#    Type: CommaDelimitedList
#    Default: subnet-0a0090421d7bd46ea
#
#  VpcID:
#    Type: String
#    Default: vpc-0b4c45cdd145ae07a
#  LoadBalancerName:
#    Type: String
#    Default: ''
#
#
#Resources:
#
#  ECSService:
#    Type: AWS::ECS::Service
#    Properties:
#      Cluster: testSerrano
#      CapacityProviderStrategy:
#        - CapacityProvider: FARGATE
#          Base: 0
#          Weight: 1
#      TaskDefinition: arn:aws:ecs:eu-west-3:968127021175:task-definition/testSerranoTask:1
#      ServiceName: testSerranoService
#      SchedulingStrategy: REPLICA
#      DesiredCount: 1
#      NetworkConfiguration:
#        AwsvpcConfiguration:
#          AssignPublicIp: ENABLED
#          SecurityGroups:
#            Ref: SecurityGroupIDs
#          Subnets:
#            Ref: SubnetIDs
#      PlatformVersion: LATEST
#      DeploymentConfiguration:
#        MaximumPercent: 200
#        MinimumHealthyPercent: 100
#        DeploymentCircuitBreaker:
#          Enable: true
#          Rollback: true
#      DeploymentController:
#        Type: ECS
#      ServiceConnectConfiguration:
#        Enabled: false
#      Tags: []
#      EnableECSManagedTags: true
#
#
#Outputs:
#
#  ClusterName:
#    Description: The cluster used to create the service.
#    Value:
#      Ref: ECSClusterName
#
#  ECSService:
#    Description: The created service.
#    Value:
#      Ref: ECSService
